In [1]:
import numpy as np

In [2]:
# create list
mylist = [1, 2, 3]

In [5]:
mylist

[1, 2, 3]

In [3]:
type(mylist)

list

In [4]:
myarray = np.array(mylist)

In [6]:
myarray

array([1, 2, 3])

In [7]:
type(myarray)

numpy.ndarray

In [11]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [15]:
# Create array of zeros 
np.zeros(shape=(10,5)) #(row, column)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
type(0)

int

In [17]:
type(0.)

float

In [18]:
type(.0)

float

In [19]:
np.ones(shape=(2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
# Create array of ones 
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [21]:
np.random.seed(101) # seed random

arr = np.random.randint(0, 100, 10)

In [22]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [25]:
arr2 = np.random.randint(0, 100, 10)

In [26]:
arr2

array([49, 83,  8, 29, 59, 34, 44, 72, 19, 10])

In [27]:
arr.max()

95

In [28]:
arr.argmax()

0

In [29]:
arr.min()

9

In [30]:
arr.argmin()

7

In [31]:
arr.mean()

60.8

In [32]:
arr.shape

(10,)

In [33]:
arr.reshape((2,5))

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [34]:
arr.reshape((3, 6))

ValueError: ignored

In [35]:
arr.reshape((2, 4))

ValueError: ignored

In [36]:
mat = np.arange(0, 100).reshape(10, 10)

In [37]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [38]:
mat.shape

(10, 10)

In [39]:
row = 0
col = 1

In [40]:
mat[row, col]

1

In [41]:
mat[6,3]

63

In [44]:
col = 2

In [45]:
mat[:, col]

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [46]:
mat[:, col].shape

(10,)

In [48]:
mat_reshape = mat[:,1].reshape(10, 1)

In [50]:
mat_reshape

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [51]:
mat_reshape.shape

(10, 1)

In [53]:
mat[0:3, 0:4] # row 0-3, col 0-4

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

In [54]:
mat[0:3, 0:4] = 0

In [55]:
mat

array([[ 0,  0,  0,  0,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0,  0, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0,  0, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [56]:
mynewmat = mat.copy()

In [57]:
mynewmat

array([[ 0,  0,  0,  0,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0,  0, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0,  0, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])